# Generated by Django 4.2.8 on 2024-01-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_school_alter_student_managers_teacher_standard'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
